-- MySQL Script generated by MySQL Workbench
-- 03/02/16 17:31:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbChronoSchedule
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbChronoSchedule` ;

-- -----------------------------------------------------
-- Schema dbChronoSchedule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbChronoSchedule` DEFAULT CHARACTER SET utf8 ;
USE `dbChronoSchedule` ;

-- -----------------------------------------------------
-- Table `dbChronoSchedule`.`Shifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbChronoSchedule`.`Shifts` ;

CREATE TABLE IF NOT EXISTS `dbChronoSchedule`.`Shifts` (
  `idTurno` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `startTime` VARCHAR(45) NULL,
  `endTime` VARCHAR(45) NULL,
  `color` VARCHAR(6) NULL,
  PRIMARY KEY (`idTurno`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idTurnos_UNIQUE` (`idTurno` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbChronoSchedule`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbChronoSchedule`.`Users` ;

CREATE TABLE IF NOT EXISTS `dbChronoSchedule`.`Users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userDni` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `realName` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `dniUser_UNIQUE` (`userDni` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbChronoSchedule`.`UserShifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbChronoSchedule`.`UserShifts` ;

CREATE TABLE IF NOT EXISTS `dbChronoSchedule`.`UserShifts` (
  `idUser` INT NOT NULL,
  `idTurno` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idTurno`, `idUser`, `date`),
  INDEX `fk_idUser_idx` (`idUser` ASC),
  CONSTRAINT `fk_idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `dbChronoSchedule`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_idTurno`
    FOREIGN KEY (`idTurno`)
    REFERENCES `dbChronoSchedule`.`Shifts` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO standard;
 DROP USER standard;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'standard' IDENTIFIED BY '1234';

GRANT SELECT ON TABLE `dbChronoSchedule`.* TO 'standard';
GRANT SELECT, INSERT, TRIGGER ON TABLE `dbChronoSchedule`.* TO 'standard';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `dbChronoSchedule`.* TO 'standard';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
